### PR TITLE
improving the PT dictionary and afixos.dat rules

### PR DESCRIPTION
**Pull request by arademaker**
This PR solves the issue TALP-UPC/FreeLing#6. More info in the issue.

### CODE REVIEW

**Comment by lluisp** [comment]
There is a mistake in your request:
* `ner-ab-poor1.dat` is the config file for `bio` NER.  To use it, it is enough to set NPDataFile in pt.cfg as you did.  BUT:  `np.dat` is the configuration file for `basic` NER. Changing type to `bio` will cause `basic`to stop working.

There are also some changes that get out of the general way of doing things:
1. Default *.cfg for all languages is PoS tagging, without sense disambiguation, and with basic NER.
    This is basically for homogeneity (some languages do not have ukb or bioNER) and for efficiency reasons (so people who run freeling for the first time on the command line get an impression of speed :-P )
    It is ok that each user customizes their config file to use bioNER, ukb, or any other option, but that should be in a private copy of the pt.cfg, not in the default config.
   Please keep the default config files with their vanilla flavour.

**Comment by arademaker** [comment]
I believe we need some guideline for contributors where all these can be made clear! ;-)

**Comment by arademaker** [comment]
BTW, in the ```np.dat``` we have:

```
## Type of NE recognizer (basic/BIO). Changing this value will require
## changing some sections in the rest of the file
<Type>
basic
</Type>
```

If this is the configuration file for the basic NER, so this section should be in another configuration file more general about NE.

**Comment by lluisp** [comment]
NER is an abstract class (actually a factory) that reads one configuration file, and creates the appropriate bioner or basic instance, depending on the <Type> in the file.

But the rest of the file needs to be consistent with the <Type>.   The sections that the underlying NE recongizer will expect to be in the file are different for each type of recognizer.  So, changing the type without changing the other sections will not work.

So, np.dat  is a NER config file that will create a basic recognizer, and ner-ab-poor1.dat is a NER config file that will create a bioner recognizer.  
You can choose which NER to use, just choosing a different config file.

I made the comment in np.dat clearer

**Pull request closed without merging**
