### PR TITLE
[WIP] Add CMake files

### PR DESCRIPTION
**Pull request by jgsogo**
Hi!

I've been playing around with FreeLing and really liked it (thanks for the great tool!), but I missed CMake files to generate and compile it, so I've been implementing a first approach to it. I suppose you know [CMake](https://cmake.org/) and all the advantages it has being almost a *de facto* standard for C++ projects.

Would you like to add it to FreeLing? If so, we can work together to tune it.

Thanks!

### CODE REVIEW

**Comment by lluisp** [comment]
Yes, I've been wanting to move to cmake for some time, but never found the moment.
I've pulled that in, thank you!
Btw, it would be great if you can keep an eye on it!  ;)

**Comment by lluisp** [comment]
I added some code to the main CMake file to install the data directories.
It still needs some work to add some CMake script to emulate the automake install-data-hook (in data/Makefile.am), which compiles the dictionaries at installation time.

**Comment by jgsogo** [comment]
Thanks! Although it was a `WIP` (Work In Progress) PR to check if there was interest in it, start talking about use cases and how to implement them... Now I know that it's a requested feature :+1:  but I think we need to talk about several questions:

 * do you want to keep `make` build system? and msvc?
 * any compilation options?
 * reorganize code to make it more CMake friendly?

**Comment by lluisp** [comment]
On 05/12/17 12:45, Javier G. Sogo wrote:
>
> Thanks! Although it was a |WIP| (Work In Progress) PR to check if 
> there was interest in it, start talking about use cases and how to 
> implement them... Now I know that it's a requested feature 👍 but I 
> think we need to talk about several questions:
>
>   * do you want to keep |make| build system? and msvc?
>
    Once it all works with CMake, we can remove these

>   * any compilation options?
>

    Now there are several configure options that define symbols used in 
the code:
       enable-traces/disable-traces: defines/undefines -DVERBOSE 
[default: undefined (i.e no verbose)]
       enable-debug/disable-debug: defines/undefines -DDEBUG [default: 
undefined (i.e. no debug)]
       enable-warnings/disable-warnings: undefines/defines -DNO_WARNINGS 
[default: undefined (i.e. warnings active)]
       enable-xpressive-regex: defines/undefines -DUSE_XPRESSIVE_REGEX  
[default: undefined (i.e. xpressive not used)]

       Windows compilation requires the synbols -DWIN32 or -DWIN64 to be 
defined too.

    Other configure options that activate/deactivate the building of 
some modules
       enable-build-tests/disable-build-tests -> builds code under 
src/tests  [default: not built]
       with-kaldi-asr  -> expects kaldi library to be installed in given 
path and compiles some dependent modules [default: not installed]

    Other configure options that do something else:
       enable-download-embeddings -> downloads big files from internet 
at installation time [default: not dowloaded]


    Compilation options should be
        -std=gnu++0x -Wall -Wno-sign-compare -fPIC -O3
    unless -DDEBUG is enabled, then it should be
       -std=gnu++0x -Wall -Wno-sign-compare -fPIC -pg -O0


>   * reorganize code to make it more CMake friendly?
>
     Uhm... that depends on how big the reorganization would be... I'd 
like to keep things close to how they are now


             Thank you !

                 Lluis




-- 
---------------------------------------------------
  Lluís Padró
  Computer Science Departament
  TALP Research Center
  UNIVERSITAT POLITÈCNICA DE CATALUNYA
  http://www.cs.upc.edu/~padro
---------------------------------------------------

**Pull request merged**
