### PR TITLE
Locale for Darwin

### PR DESCRIPTION
**Pull request by ambs**
Not ready. Just to allow the comparison of all my changes.

### CODE REVIEW

**Comment by ambs** [comment]
@lluisp, this shouldn't happen, right?
`````````
$ cat teste.txt
O coração é um órgão frágil.
O CORAÇÃO É UM ÓRGÃO FRÁGIL.

$ /opt/FreeLing4/bin/analyze -f /opt/FreeLing4/share/freeling/config/pt.cfg < teste.txt
O o DA0MS0 0.950254
coração coração NCMS000 1
é ser VMIP3S0 1
um um DI0MS0 0.877848
órgão órgão NCMS000 1
frágil frágil AQ0CS00 1
. . Fp 1

O o DA0MS0 0.950254
CORAÇÃO_É_UM_ÓRGÃO_FRÁGIL coração_é_um_órgão_frágil NP00000 1
. . Fp 1
```````

**Comment by ambs** [comment]
(but unicode and uppercase/lowercase is working, what might be wrong at this moment?)

**Comment by lluisp** [comment]
That is rigth,  It is the NE reconizer being confused by so many uppercase letters.
You can control that with the option TitleLimit in np.dat configuration file.

**Comment by lluisp** [comment]
It all looks great, let me know when you are done.

**Comment by ambs** [comment]
Sorry, didn't have the time to remove the comments today. If you did not remove them yet, let me know, nd I'll prepare a new PR.

**Comment by lluisp** [comment]
I already did. 
 I am checking it still works on linux before pushing it
thanks!

**Pull request merged**
