### PR TITLE
small dict contributions

### PR DESCRIPTION
**Pull request by arademaker**
two verb forms and two noun forms.

### CODE REVIEW

**Comment by lluisp** [comment]
thanksª

(Althouhg "snowsuit" can be properly analyzed activating the "compounds" module in the dictionary)

**Comment by arademaker** [comment]
@lluisp nice to know about the compound module. I have just tested it with

```
# echo 'Four children are doing backbends in the gym.' | analyze -f en.cfg
Four 4 Z 0.999648 -
children child NNS 1 09917593-n:0.00955591/09918248-n:0.0082921/09918554-n:0.00816267/09918762-n:0.00767976
are be VBP 1 02604760-v:0.00343593/02655135-v:0.00277136/02702508-v:0.00272231/02603699-v:0.00271386/02445925-v:0.0026967/02620587-v:0.0026879/02744820-v:0.00248675/02664769-v:0.00247956/02268246-v:0.00246787/02614181-v:0.00243165/02697725-v:0.00242333/02749904-v:0.00232072/02616386-v:0.00230945
doing do VBG 0.999182 01712704-v:0.00286462/02561995-v:0.0027777/00010435-v:0.0027659/02669789-v:0.00276031/02568672-v:0.0027397/01645601-v:0.00254672/02523221-v:0.00253454/02617567-v:0.00253097/01619014-v:0.00251956/02560585-v:0.00250854/02709107-v:0.00249544/00038849-v:0.00247717/01841772-v:0.00234771
backbends back_bend NNS 0.72824 -
in in IN 0.987107 -
the the DT 1 -
gym gym NN 1 03472112-n:0.0314372
. . Fp 1 -
```

So it seems that with the compound module turned on, it was able to analyse the _backbends_  right.  But notice that with the underscore the ukb module will not be able to find the correct sense for it (http://wnpt.brlcloud.com/wn/synset?id=00434231-n). I read the (docs)[https://talp-upc.gitbooks.io/freeling-user-manual/content/modules/dictionary.html] but didn't understand how to suppress the underscore in the lemma.

**Comment by lluisp** [comment]
The lemma in WordNet is "backbend", not "back_bend", that is why it is not found

So, the problem in this case is a discrepancy between FreeLing morphological dictionary and WN dictionary.  The best way to fix this would be making sure that the morphological dictionary contains 'backbend' and any other missing wordnet entry (or at least those that are single words in WN)

The compounds module would help you in the opposite direction:  When you glue toghether something that should be separated (e.g. if you write  "eyecontact", it will be lemmatized to eye_contact, and found in WN)

However, note that you can glue things like "kingslayer", which will be lemmatized to "king_slayer", which is not in WN.  So, those cases should be approached splitting the word in several pieces and analyzing them separately.  FreeLing is not that daring, and leaves this decision to the calling application.

**Comment by vcvpaiva** [comment]
@lluisp  wouldn't it be a good idea to make sure that FreeLing has all the lemmas that Princeton WordNet has? I think it doesn't and it causes problems when trying to find the senses. For example many adjectives (that are indeed derived from participles) like "bored", "animated" are  considered adjectives, but lemmatized as verbs by Freeling, which gives a strange situation of the adjective "bore", or the adjective "wheel".

**Comment by arademaker** [comment]
@vcvpaiva this is just a matter of contribute to the EN dictionary. Files are (here)[https://github.com/TALP-UPC/FreeLing/tree/master/data/en/dictionary/entries].

**Comment by vcvpaiva** [comment]
@arademaker what I am asking @lluisp is whether he has any reason or principle for not doing a direct mapping of PWN, given that he does provide the service of senses using PWN.

**Comment by arademaker** [comment]
@lluisp 

> The lemma in WordNet is "backbend", not "back_bend", that is why it is not found

Yes, I understood it, that is why I wrote to you in the first place! ;-)

> The best way to fix this would be making sure that the morphological dictionary contains 'backbend' and any other missing wordnet entry (or at least those that are single words in WN)

This is precisely what I did with 'snowsuit' when you said that I should have considered the compound module. Or maybe I didn't understand your advice.

> The compounds module would help you in the opposite direction: When you glue toghether something that should be separated (e.g. if you write "eyecontact", it will be lemmatized to eye_contact, and found in WN)

Wow! I didn't know that tokens glued together by underscore are still matched against the WN (or any other sense dictionary). So the underscore is really a special character for many freeling modules. 

> However, note that you can glue things like "kingslayer", which will be lemmatized to "king_slayer", which is not in WN. So, those cases should be approached splitting the word in several pieces and analyzing them separately. FreeLing is not that daring, and leaves this decision to the calling application.

I know, this is the Freeling's philosophy that you always make clear! ;-) Not clear however how to actually take each decision. In your example, with the compound module we would have "kingslayer" lemmatized to "king_slayer". The application would need to check all these tokens to split them into two tokens with the lemas "king" and "slayer", right? That would work for the WSD module because both lemmas are in the WN. But how to split a token like this  with the Freeling API? This is related with my lack of understanding about how to use the Freeling data structures between Freeling modules calls.

The other possibility would be to ensure that "kingslayer" is not splitted, maybe turning the compoud module off, adding this word it in the EN dictionary or undoing the compound module analysis in the token.

**Comment by arademaker** [comment]
@vcvpaiva ok, so maybe @lluisp  can add something. But I suspect that it is just something that he would be happy to have someone contributing to it. Almost all languages' data were contributions to Freeling project by other researchers.

**Comment by lluisp** [comment]
>     The best way to fix this would be making sure that the
>     morphological dictionary contains 'backbend' and any other missing
>     wordnet entry (or at least those that are single words in WN)
>
> This is precisely what I did with 'snowsuit' when you said that I 
> should have considered the compound module. Or maybe I didn't 
> understand your advice.
>
   Yes,you did it right.
>
>     The compounds module would help you in the opposite direction:
>     When you glue toghether something that should be separated (e.g.
>     if you write "eyecontact", it will be lemmatized to eye_contact,
>     and found in WN)
>
> Wow! I didn't know that tokens glued together by underscore are still 
> matched against the WN (or any other sense dictionary). So the 
> underscore is really a special character for many freeling modules.
>
   Some entries in WN are single words, other (such as "eye contact") 
are multiwords. When dumped to freeling files, whitespaces in WN 
multiwords are converted to underscores.
>
>     However, note that you can glue things like "kingslayer", which
>     will be lemmatized to "king_slayer", which is not in WN. So, those
>     cases should be approached splitting the word in several pieces
>     and analyzing them separately. FreeLing is not that daring, and
>     leaves this decision to the calling application.
>
> I know, this is the Freeling's philosophy that you always make clear! 
> ;-) Not clear however how to actually take each decision. In your 
> example, with the compound module we would have "kingslayer" 
> lemmatized to "king_slayer". The application would need to check all 
> these tokens to split them into two tokens with the lemas "king" and 
> "slayer", right? That would work for the WSD module because both 
> lemmas are in the WN. But how to split a token like this with the 
> Freeling API? This is related with my lack of understanding about how 
> to use the Freeling data structures between Freeling modules calls.
>
    So far, FreeLing API does not provide a direct way to do that. You 
would need to create two new word objects, assign them lemmas "king" and 
"slayer", and the right PoS, replace the original word in the sentece 
with the two new words, and send the sentence to WSD.
   It is not difficult, but surely the API could provide it.

> The other possibility would be to ensure that "kingslayer" is not 
> splitted, maybe turning the compoud module off, adding this word it in 
> the EN dictionary or undoing the compound module analysis in the token.
>
    Yes, but the problem is that the possible compounds are infinite, 
you can not have them all in the dictionary...

**Comment by vcvpaiva** [comment]
@lluisp yes, sure

>Yes, but the problem is that the possible compounds are infinite,
you can not have them all in the dictionary...

the compounds are infinite, but some are lexicalized, some are not. 
the boundary is fuzzy. most people think that the collection of compounds in PWN is too small.
what I was suggesting was to have *at least* the ones in PWN in the dictionary, as they're a baseline.

what you haven't replied is whether there are (or not) reasons not to have the PWN baseline in place.
hopefully @arademaker is right, there are no trade-offs, it's just that no one could be bothered, yet, to make sure that all lemmas from PWN are accounted for in FreeLing.

**Pull request merged**
