### PR TITLE
Delete the unused changelog and news files

### PR DESCRIPTION
**Pull request by bryant1410**
Delete the changelog and news files, as they're not used.

### CODE REVIEW

**Comment by lluisp** [comment]
I added them back, since automake fails if they are not there.

**Comment by bryant1410** [comment]
I think this is not a good reason to add them back. The automake should be fixed. Why the automake fails?

**Comment by lluisp** [comment]
automake is not a part of FreeLing. It is a quite standard GNU tool that automatically generates Makefiles: see https://www.gnu.org/software/automake/

Questions about why it works this way, or suggestions about what should be fixed, should be addressed to automake developers.

**Comment by bryant1410** [comment]
But automake always enforces you to have these files?

**Comment by lluisp** [comment]
Yes, it does.  It fails with an error if they are not there.

It seems it should have an option `--add-missing` that should create the files, but I didn't manage to make it work.
If you find a more elegant solution, please post it.

**Comment by lluisp** [comment]
I found that automake can be configured to ignore those files.
So, I removed them again and changed configure.ac

Please try again from scratch to check it works:
```
make distclean
git pull
autoreconf --instal
./configure; makemake install
```

**Comment by arademaker** [comment]
it worked for me.

**Pull request merged**
